name: Release Canary

on:
  push:
    branches:
      - develop
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: release canary
    runs-on: ubuntu-latest
    container: node:22-bullseye
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Install dependencies
        run: npm i

      - name: Enter prelease mode
        continue-on-error: true
        run: npm run canary:enter

      - name: Set Git identity
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          version: npm run version
          title: "chore(root): version apps"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
